# note: simple config for dev.
# it puts everything you might want for dev into the default environment

[workspace]
authors = ["Chris Barker <chris.barker@noaa.gov>"]
channels = ["conda-forge"]
name = "nc_particles"
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
version = "0.1.0"

[pypi-dependencies]
nc_particles = { path = ".", editable = true }

[dependencies]
# core
python = ">=3.11,<3.15"
numpy = ">=2"
xarray = "*"
netcdf4 = "*"

# dev
ipython = "*"
pytest = "*"
pytest-cov = "*"


# [feature.py311.dependencies]
# python = "3.11.*"


# [feature.py314.dependencies]
# python = "3.14.*"


[tasks]
test = { cmd = "pytest --pyargs nc_particles"}
#test3 = { cmd = "pytest --pyargs nc_particles", depends-on = ["dev"] }



