[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"


[project]
name = "nc_particles"
authors = [
  {name = "Christopher H. Barker", email = "chris.barker@noaa.gov"},
]
description = "Code for working with the nc_particles format for storing particle tracking model results in netcdf"
dynamic = ["version"]
readme = "README.md"
license = {text = "CC-0 -- Public Domain"}
dependencies = [
  "numpy>=2",
  "xarray",
  "netCDF4",
]
requires-python = ">= 3.12"

classifiers = [
  "Development Status :: 3 - Alpha",

  "Intended Audience :: Science/Research",
  "Topic :: Software Development :: Build Tools",
  "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]

[project.urls]
Repository = "https://github.com/NOAA-ORR-ERD/nc_particles"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/nc_particles/_version.py"

[tool.hatch.version.raw-options]
root = ".."

[tool.hatch.build.targets.sdist]
# include = [
#     "python_implementation/nc_particles",
# ]
ignore-vcs = false # so it will use .gitignore

[tool.hatch.build.targets.wheel]
packages = ["src/nc_particles"]

